### ISSUE TITLE
setup.sh not working as described

### ISSUE THREAD

**Issue by Dynatrace-BrianWilson** [dt-kube-demo/setup-infra#7]
In the readme, it instructs the user to enter a deployment, like eks.
If a user runs `./setup.sh eks` and then selects a step, they get an error:
`=============================================
Missing or Invalid 'deployment type' argument. 
Valid 'deployment types' are:

eks = AWS
=============================================`

If a user just runs `./setup.sh` without deployment type argument, it works.

**Comment by robertjahn** [comment]
I had hardcoded eks as temp measure.  in this update 
https://github.com/dt-kube-demo/setup-infra/commit/e92c7c06dc772b766da3b920f043d0a4a10a3878

I changed it so that you need to enter the deployment argument once.  it will be saved and re-read out of creds.json so that you dont have to keep re-entering it
